[package]
name = "kubeflare-controller-k8s-api"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
kube = { version = "0.60.0", features = ["derive"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1"
schemars = "0.8"
